DictApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('words.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'users'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('', views.HomeView.as_view(), name='home'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('delete_img/', views.delete_profile_image, name='delete-profile-image'),


    path('password_reset', views.password_reset, name='password-reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),
         name='password-reset-done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html',
                                                     success_url=reverse_lazy("users:password-reset-complete")),
         name='password-reset-confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
         name='password-reset-complete'),


    # path('profile/update/', views.user_update_view, name='update-user')
]

words/urls.py
from django.urls import path

from .views import FolderCreateListView, FolderRetrieveUpdateView, WordCreateView, FolderDestroyView


app_name = 'words'
urlpatterns = [
    path('folder/<int:pk>', FolderRetrieveUpdateView.as_view(), name='folder-ru'),
    path('folder', FolderCreateListView.as_view(), name='folder-cl'),
    path('folder/delete/<int:pk>', FolderDestroyView.as_view(), name='folder-d'),

    path('word', WordCreateView.as_view(), name='word-c'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    image = models.ImageField(upload_to='profile/', blank=True, null=True)
    job = models.CharField(max_length=255, blank=True, default='')

    def __str__(self):
        return self.username

words/models.py
from django.db import models


class Folder(models.Model):
    name = models.CharField(max_length=255)


class Word(models.Model):
    word = models.CharField(max_length=255)
    translation = models.CharField(max_length=255, blank=True)
    description = models.TextField()
    folder = models.ForeignKey(to=Folder, on_delete=models.CASCADE, related_name='word')

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'image', 'job')

words/forms.py
from django import forms

from .models import Folder, Word


class FolderForm(forms.ModelForm):

    class Meta:
        model = Folder
        fields = ['name']


class WordForm(forms.ModelForm):

    class Meta:
        model = Word
        fields = ['word', 'translation', 'description', 'folder']

user/views.py
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.db.models.query_utils import Q

from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import CustomUser


class HomeView(View):
    def get(self, request):
        return render(request, 'home.html')


class RegisterView(View):
    def get(self, request):
        return render(request, 'register.html')

    def post(self, request):
        user = CustomUserCreationForm(request.POST)
        if user.is_valid():
            user.save()
            return redirect('users:login')
        print(user.errors)
        return redirect('users:register')


@login_required
def profile_view(request):
    if request.method == 'POST':
        user = CustomUser.objects.get(pk=request.user.pk)
        update_user = CustomUserChangeForm(request.POST, request.FILES, instance=user)
        if update_user.is_valid():
            update_user.save()
        print(update_user.errors)
    user = CustomUser.objects.get(pk=request.user.pk)
    return render(request, 'profile.html', {'user': user})


@login_required
def delete_profile_image(request):
    user = CustomUser.objects.get(pk=request.user.pk)
    user.image.delete()
    return redirect('users:profile')


def password_reset(request):
    if request.method == 'POST':
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_user = CustomUser.objects.filter(Q(email=data))
            if associated_user.exists():
                for user in associated_user:
                    subject = "Password Reset Requested"
                    email_template_name = "password/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect('users:password-reset-done')
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="password/password_reset.html",
                  context={"password_reset_form": password_reset_form})

words/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Folder, Word
from .forms import FolderForm, WordForm


def get_folders():
    return Folder.objects.all()


def get_words(pk):
    return Word.objects.filter(folder_id=pk)


class FolderCreateListView(View, LoginRequiredMixin):

    def get(self, request):
        context = {
            'folders': get_folders()
        }
        return render(request, 'folder.html', context)

    def post(self, request):
        form = FolderForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('words:folder-cl')


class FolderRetrieveUpdateView(View, LoginRequiredMixin):

    def get(self, request, pk):
        try:
            folder = Folder.objects.get(pk=pk)
        except:
            return redirect('users:home')
        context = {
            'folder_id': pk,
            'words': get_words(pk)
        }
        return render(request, 'word.html', context)

    def post(self, reqeuest):
        form = FolderForm(reqeuest.POST)
        if form.is_valid():
            form.save()
        return redirect('users:home')


class WordCreateView(View, LoginRequiredMixin):

    def post(self, request):
        form = WordForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect("words:folder-ru", pk=request.POST['folder'])


class FolderDestroyView(View):

    def get(self, request, pk):
        folder = Folder.objects.get(pk=pk)
        folder.delete()
        return redirect('words:folder-cl')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block style %}{% endblock %}
    </head>
<body>

{% block body %} {% endblock %}
</body>
</html>

templates/folder.html
{% extends 'base.html' %}


{% block title %}
    Folders
{% endblock %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}

{% block body %}
    {% include 'navbar.html' %}
    {% if user.is_authenticated %}
        {% for folder in folders %}
            <div class="folder">
                <h3>
                    <a href="{% url 'words:folder-ru' folder.pk %}">{{ folder.name }}</a>
                </h3>
                <a class="delete-icon" href="{% url 'words:folder-d' folder.pk %}"><img src="{% static 'images/trash.png' %}" alt="" height="32px"></a>
            </div>
        {% endfor %}
        <div class="folder" id="create-button">
            <button onclick="onClickCreateButton()">
                <img src="{% static 'images/add.png' %}" class="hover-logo" alt="Adding folder" height="64px">
            </button>
         </div>
        <div class="container-fluid folder" id="create-form">
             <form action="{% url 'words:folder-cl' %}" method="POST">{% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        <div class="row justify-content-center">
                            <input type="text" name="name" id="" placeholder="Folder name">
                        </div>
                    </div>
                </div>
                <button type="submit">Create</button>
                <button type="button" onclick="cancelCreateForm()">Cancel</button>
            </form>
        </div>
    {% else %}
        <h1>Salom</h1>
    {% endif %}
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}


{% block title %}
    Home
{% endblock %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}

{% block body %}
    {% include 'navbar.html' %}
    {% if user.is_authenticated %}

    {% else %}
        <h1>Login or Register</h1>
        <img src="" alt="">
    {% endif %}
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}



{% block title %}
    Login
{% endblock %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/login/login.css' %}">
{% endblock %}

{% block body %}
    <div class="center">
      <h1>Login</h1>
      <form method="post"> {% csrf_token %}
        <div class="txt_field">
          <input type="text" name="username" required>
          <span></span>
          <label>Username</label>
        </div>
        <div class="txt_field">
          <input type="password" name="password" required>
          <span></span>
          <label>Password</label>
        </div>
        <div class="pass"><a class="pass" href="{% url 'users:password-reset' %}">Forgot Password?</a></div>
        <input type="submit" value="Login">
        <div class="signup_link">
          Not a member? <a href="{% url 'users:register' %}">Signup</a>
        </div>
      </form>
    </div>
{% endblock %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light nav-bg">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'users:home' %}">DictApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'words:folder-cl' %}">Folders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}">
                            <img src="{% static 'images/profile.png' %}" alt="profile" height="24px">
                        </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/password/password_reset.html
{% extends 'base.html' %}

{% block title %}
    Password reset
{% endblock %}

{% block style %}
    {% load static %}
{#    <link rel="stylesheet" href="{% static 'css/styles.css' %}">#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}

{% block body %}
    <div class="container p-5">
  	 	<h2 class="font-weight-bold mt-3">Reset Password</h2>
		<hr>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST"> {% csrf_token %}
            <input type="email" name="email">
            <button class="btn btn-primary" type="submit">Send email</button>
        </form>
  	</div>
{% endblock %}
%}

templates/password/password_reset_complete.html
{% extends "base.html" %}

{% block style %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}

{% block body %}
  
  <!--Password Reset Complete-->
    <div class="container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>                 
        <a href="{% url 'users:login' %}" class="btn btn-primary">Log in</a>
    </div>

{% endblock %}

templates/password/password_reset_confirm.html
{% extends "base.html" %}

{% block style %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}

{% block body %}

  <!--Password Reset Confirm-->
   <div class="container p-5">
	    <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
		<hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>
   </div>

{% endblock %}

templates/password/password_reset_done.html
{% extends 'base.html' %}

{% block title %}
    Password reset done!
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}

{% block body %}
    <div class="container p-5">
  	<h2 class="font-weight-bold mt-3">Password reset sent</h2>
		<hr>
		<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
  </div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block title %}
    Profile
{% endblock %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}

{% block body %}

    {% include 'navbar.html' %}

    <section>

        <div class="container py-5">
            <div class="row">
                <div class="col-lg-4">
                    <div class="card mb-4">
                        <div class="card-body text-center">
                            {% if user.image %}
                                <img src="{{ user.image.url }}" alt="avatar"  class="rounded-circle img-fluid" style="height: 150px;">
                                <a href="{% url 'users:delete-profile-image' %}" class="btn btn-outline-danger my-3">Remove image</a>
                            {% else %}
                                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"  class="rounded-circle img-fluid" style="width: 150px;">
                            {% endif %}
                            {% if user.first_name or user.last_name %}
                                <h5 class="my-3">{{ user.first_name }} {{ user.last_name }}</h5>
                            {% endif %}
                            <h6 class="my-3 text-secondary" >@{{ user.username }}</h6>
                            {% if user.job %}
                            <p class="text-muted mb-1">{{ user.job }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <form method="post" enctype="multipart/form-data"> {% csrf_token %}
                        <div class="card mb-4">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <p class="mb-0">Username</p>
                                    </div>
                                    <div class="col-sm-9">
                                        <p class="text-muted mb-0">{{ user.username }}</p>
                                    </div>
                                </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Email</p>
                                </div>
                                <div class="col-sm-9">
                                    <input class="px-1 w-50" type="email" name="email" value="{{ user.email }}">
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">First name</p>
                                </div>
                                <div class="col-sm-9">
                                    <input class="px-1 w-50" type="text" name="first_name" value="{{ user.first_name }}">
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Last name</p>
                                </div>
                                <div class="col-sm-9">
                                    <input class="px-1 w-50" type="text" name="last_name" value="{{ user.last_name }}">
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Job</p>
                                </div>
                                <div class="col-sm-9">
                                    <input class="px-1 w-50" type="text" name="job" value="{{ user.job }}">
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Upload image</p>
                                </div>
                                <div class="col-sm-9">
                                    <input type="file" name="image">
                                </div>
                            </div>
                            <button type="submit" class="btn btn-outline-primary mt-3">Save</button>
                            <button type="reset" class="btn btn-outline-danger mt-3">Cancel</button>
                          </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/register.html
{% extends 'base.html' %}



{% block title %}
    Register
{% endblock %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/login/login.css' %}">
{% endblock %}

{% block body %}
    <div class="center">
      <h1>Register</h1>
      <form action="{% url 'users:register' %}" method="post"> {% csrf_token %}
        <div class="txt_field">
          <input type="text" name="username" required>
          <span></span>
          <label>Username</label>
        </div>
        <div class="txt_field">
          <input type="text" name="email" required>
          <span></span>
          <label>Email</label>
        </div>
        <div class="txt_field">
          <input type="password" name="password1" required>
          <span></span>
          <label>Password</label>
        </div>
        <div class="txt_field">
          <input type="password" name="password2" required>
          <span></span>
          <label>Password</label>
        </div>
        <input type="submit" value="Register">
        <div class="signup_link">
          Have you account? <a href="{% url 'users:login' %}">Sign in</a>
        </div>
      </form>
    </div>
{% endblock %}

templates/word.html
{% extends 'base.html' %}


{% block title %}
    Folders
{% endblock %}

{% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}

{% block body %}
    {% include 'navbar.html' %}

    {% if user.is_authenticated %}
        {% for word in words %}
            <div class="word">
                <p class="word-text">{{ word.word }}</p>
                <p class="word-translation">{{ word.translation }}</p>
                <p class="word-description">{{ word.description }}</p>
            </div>
        {% endfor %}
        <div class="folder" id="create-button">
            <button onclick="onClickCreateButton()">
                <img src="{% static 'images/add.png' %}" class="hover-logo" alt="Adding folder" height="64px">
            </button>
         </div>
        <div class="container-fluid folder" id="create-form">
            <form action="{% url 'words:word-c' %}" method="POST">{% csrf_token %}
                <input type="hidden" name="folder" value="{{ folder_id }}">
                <div class="row">
                    <div class="col-6">
                        <div class="row justify-content-end">
                            <input type="text" name="word" id="" placeholder="Word">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="row justify-content-start">
                            <input type="text" name="translation" id="" placeholder="Translation of Word">
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-6">
                        <textarea class="description" name="description" placeholder="Description of word" cols="30" rows="5"></textarea>
                    </div>
                </div>
                <button type="submit">Create</button>
                <button type="button" onclick="cancelCreateForm()">Cancel</button>
            </form>
        </div>
    {% else %}
        <h1>Salom</h1>
    {% endif %}
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}